# ----
# Site

title: JSAI
url: "https://long-pig.cloudvent.net"
baseurl:
google_analytics_key:
show_full_navigation: true
excluded_in_search: true


# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: GuanDan platform for AI
author:
  name: duofeng Wu
  email: wuguduofeng@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: NJUPT
  links:
    - http://gameai.njupt.edu.cn/index.html

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
